### ISSUE TITLE
Support for 3.3.0

### ISSUE THREAD

**Issue by danboh** [masweetman/issue_charts#8]
Hi,

I just tried adding this plugin to my 3.3.0 project, and it seems to be working fine. However, I did notice that after installing the plugin, in the Activity tab, on the right side menu there's an error that reads:

> translation missing: en.label_show_user_activity

Thoughts?

**Comment by masweetman** [comment]
That's definitely not my plugin--mine doesn't make any changes to the Activity page and I don't have any labels called "label_show_user_activity". You probably have another plugin that is causing that issue, since label_show_user_activity doesn't appear anywhere in the Redmine core either. This issue happens when the code calls for l(:label_show_user_activity) without having defined that label in one of the locale files (plugins/[plugin_name]/config/locales/*.yml).

A quick search uncovers a plugin called "redmine_my_page" in github which has the same problem you are describing. That could be what's causing it.

**Comment by danboh** [comment]
Oh, interesting. I'll look it up.

In that case you can close this one, and add support to 3.3.0

Thanks a lot for this!
